### ISSUE TITLE
Please update to swift 3.1 (till 2017-03-29)

### ISSUE THREAD

**Issue by tianyouhui** [bhuztez/swift-cflite#1]
It's a very great project for swift-cflite... and will you update to latest swift

**Comment by bhuztez** [comment]
At very beginning, I thought it was not very hard to make toll-free bridging work on non-Apple platforms, but I was wrong. It turns out that it is intentionally hard-coded in the compiler that swift won't accept Objective-C header on non-Apple platforms. Also, GNUstep is mostly Objective-C, there is no CoreFoundation alternative in GNUstep. This is a dead end.

**Comment by tianyouhui** [comment]
OK,I got.
